[project]
name = "pyrosper-fastapi"
dynamic = ["version"]
description = "Pyrosper FastAPI Tools"
readme = "README.md"
authors = [
    { name = "Robert Plummer", email = "robertleeplummerjr@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pyrosper>=0.1.9.post1",
    "starlette>=0.52.1",
]

[dependency-groups]
dev = [
    "pyright>=1.1.408",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "setuptools>=82.0.0",
]


[build-system]
requires = ["setuptools", "wheel", "setuptools-scm"]
build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
addopts = "-n auto"

[tool.setuptools_scm]
version_scheme = "post-release"
local_scheme = "no-local-version"
version_file = "src/pyrosper_fastapi/version.py"

[tool.setuptools.packages.find]
where = ["src"]
